# EE 379K Lab 3
## Rohan Nagar and Wenyang Fu

In [1]:
import numpy as np

# Question 1: Jaccard Similarity

In [2]:
# def jaccard_similarity(x, y, z):
#     intersection_cardinality = len(set.intersection(*[set(x), set(y), set(z)]))
#     union_cardinality = len(set.union(*[set(x), set(y), set(z)]))
#     return intersection_cardinality / float(union_cardinality)

# jaccard_similarity(['nike', 'running', 'shoe'],
#                    ['nike', 'black', 'running', 'shoe'],
#                    ['nike', 'blue', 'jacket', 'adidas'])

def jaccard_similarity(x, y, z):
    intersection_cardinality = len(x & y & z)
    union_cardinality = len(x | y | z)
    return intersection_cardinality / float(union_cardinality)

jaccard_similarity({'nike', 'running', 'shoe'},
                   {'nike', 'black', 'running', 'shoe'},
                   {'nike', 'blue', 'jacket', 'adidas'})

0.14285714285714285

# Question 2: Minhash

### Part A: Create the characteristic matrix with the alphabet as the seven words {'nike', 'running', 'shoe', 'black', 'blue', 'jacket', 'adidas'}

In [3]:
char_matrix = np.array([['nike',1,1,1],
                         ['running',1,1,0],
                         ['shoe',1,1,0],
                         ['black',0,1,0],
                         ['blue',0,0,1],
                         ['jacket',0,0,1],
                         ['adidas',0,0,1]])
print(char_matrix)

[['nike' '1' '1' '1']
 ['running' '1' '1' '0']
 ['shoe' '1' '1' '0']
 ['black' '0' '1' '0']
 ['blue' '0' '0' '1']
 ['jacket' '0' '0' '1']
 ['adidas' '0' '0' '1']]


### Part B: For a random permutation of the seven alphabet elements, find a way to compute the first non-zero element of each column (each set) under the permutation.

In [4]:
def first_elements(permutation):
    first = []
    for column in permutation.T:
        for i, elem in enumerate(column):
            if elem == '1':
                first.append(permutation.T[0][i])
                break
    return first
    
permutation = np.random.permutation(char_matrix)
first_elements(permutation)

['nike', 'nike', 'adidas']

### Part C: Instead of choosing a random permutation, use the hash function $h(x) = 3x + 2 (mod 7)$.

In [5]:
def hash_func(x):
    return (3 * x + 2) % 7

hashf = np.vectorize(hash_func) # Vectorized function for hardware-parallel computation

def hashed_permutation(char_matrix):
    num_sets = char_matrix.shape[0]
    idxs = hashf(np.arange(num_sets))
    print(idxs)
    return char_matrix[idxs]

hashed_matrix = hashed_permutation(char_matrix)
print(hashed_matrix)
print(type(hashed_matrix))

first_elements(hashed_matrix)

[2 5 1 4 0 3 6]
[['shoe' '1' '1' '0']
 ['jacket' '0' '0' '1']
 ['running' '1' '1' '0']
 ['blue' '0' '0' '1']
 ['nike' '1' '1' '1']
 ['black' '0' '1' '0']
 ['adidas' '0' '0' '1']]
<class 'numpy.ndarray'>


['shoe', 'shoe', 'jacket']

### Part D: Generate your own hash functions of the form $h(x) = ax + b (mod 7)$ by choosing $a$ and $b$ at random from the set $\{0, 1, ..., 6\}$. Do this twenty times to estimate the Jaccard Similarity of the three sets. How closely do you approximate the true values, computed in question one?

In [6]:
choices = np.arange(7)
s1, s2, s3 = (  {'nike', 'running', 'shoe'},
                {'nike', 'black', 'running', 'shoe'},
                {'nike', 'blue', 'jacket', 'adidas'}
             )
alphabet = ['nike', 'running', 'shoe', 'black', 'blue', 'jacket', 'adidas']

def gen_hash_func(choices):
    a = np.random.choice(choices)
    b = np.random.choice(choices)

    hash_func = lambda x: (a * x + b) % 7
    return hash_func

hash_funcs = [gen_hash_func(choices) for _ in range(20)]
alphabet_dict = dict(zip(alphabet, range(len(alphabet)))) # Integer mapping of the alphabet.

s1 = {alphabet_dict[elem] for elem in s1}
s2 = {alphabet_dict[elem] for elem in s2}
s3 = {alphabet_dict[elem] for elem in s3}

sets = (s1, s2, s3) # Tuple of 3 sets

def jac_sim_experiment(sets, hashf):
    hashed = [{hashf(e) for e in s}
                        for s in sets]
    
    jaccard_score = jaccard_similarity(hashed[0], hashed[1], hashed[2])
    return jaccard_score

experimental_avg = sum([jac_sim_experiment(sets, f) for f in hash_funcs]) / 20
print(experimental_avg)


0.3571428571428573


### Running the experiment a few times, the experimental score ranges anywhere from perfect (1/7) to around .48. So its usually not too accurate.

# Question 3: Implementing Minhash

### Repeat the above where instead of permuting the entire characteristic matrix, implement the algorithm described in Chapter 3 of MMDS for implementing Minhash.

In [7]:
def minhash(a, hash_funcs):
    """ This implementation of MinHash
    will take a 2-dimensional characteristic matrix 
    and return the hashed signature matrix.
    
    a - 2-dim ndarray 
    hash_funcs - set of hash functions to use
    """
    alphabet_size = a.shape[0]
    num_sets = a.shape[1]
    n = len(hash_funcs)
    
    sig = np.zeros((n, num_sets)) # preallocate Signature matrix
    sig.fill(np.inf)
    
    for r in range(alphabet_size):
        row_hashes = np.array([hash_funcs[i](r) for i in range(n)])
        col_idxs = np.where(a[r, :] == '1')[0] # Columns to fill in
        num_idxs = len(col_idxs)
        sig[:, col_idxs] = np.minimum(sig[:, col_idxs], 
                                      np.array([row_hashes] * num_idxs).T)
    return sig

char_matrix = np.array([['nike',1,1,1],
                         ['running',1,1,0],
                         ['shoe',1,1,0],
                         ['black',0,1,0],
                         ['blue',0,0,1],
                         ['jacket',0,0,1],
                         ['adidas',0,0,1]])
sig = minhash(char_matrix[:, 1:] ,hash_funcs[:5])

sig

array([[ 4.,  0.,  1.],
       [ 4.,  3.,  0.],
       [ 2.,  0.,  1.],
       [ 6.,  6.,  6.],
       [ 6.,  6.,  6.]])

In [8]:
num_rows, num_cols = sig.shape

sets = [set(sig[i, :]) for i in range(num_cols)]
jaccard_score = len(set.intersection(*sets)) / len(set.union(*sets))
jaccard_score

0.2

# Question 4: More Minhash (Shingling)

### Part A: Load the 5 article excerpts in $\tt{Lab3articles-5.txt}$.

In [9]:
documents = []
with open('Lab3articles-5.txt', 'r') as f:
    for line in f:
        documents.append(line.strip())
    
print(documents[0])

t120 The Supreme Court in Johnnesberg on Friday postponed until March 14 a hearing on a petition by government minister Winnie Mandela to prevent police reading documents seized from her home, the SAPA news agency reported. David Wright and Carlos Delgado homered and Jorge Sosa won for the sixth time as the New York Mets snapped a four-game losing streak with a 3-0 victory over Detroit on Friday night. US Defense Secretary Robert Gates said on Sunday that Iran was not yet able to make a nuclear weapon and that its program was progressing slower than Tehran expected. A Palestinian suicide bomber blew himself up in a crowded hotel dining room here Wednesday evening just as more than 200 people gathered for their Passover holiday meal, killing at least 19 and wounding more than 100 others, many of them children. OPEC kingpin Saudi Arabia signalled Tuesday it could act alone to meet a predicted increase in demand for oil, as it pushed hesitant fellow members of the cartel to raise producti

### Part B: Use $\tt{stopwords}$ from $\tt{nltk.corpus}$ to strip the stopwords from the 5 articles.

In [10]:
from nltk.corpus import stopwords

stop_words = stopwords.words('english')

stripped_documents = []
for document in documents:
    excerpt = [word for word in document.split() if word not in stop_words]
    stripped_documents.append(excerpt)
    
print(stripped_documents[0])

['t120', 'The', 'Supreme', 'Court', 'Johnnesberg', 'Friday', 'postponed', 'March', '14', 'hearing', 'petition', 'government', 'minister', 'Winnie', 'Mandela', 'prevent', 'police', 'reading', 'documents', 'seized', 'home,', 'SAPA', 'news', 'agency', 'reported.', 'David', 'Wright', 'Carlos', 'Delgado', 'homered', 'Jorge', 'Sosa', 'sixth', 'time', 'New', 'York', 'Mets', 'snapped', 'four-game', 'losing', 'streak', '3-0', 'victory', 'Detroit', 'Friday', 'night.', 'US', 'Defense', 'Secretary', 'Robert', 'Gates', 'said', 'Sunday', 'Iran', 'yet', 'able', 'make', 'nuclear', 'weapon', 'program', 'progressing', 'slower', 'Tehran', 'expected.', 'A', 'Palestinian', 'suicide', 'bomber', 'blew', 'crowded', 'hotel', 'dining', 'room', 'Wednesday', 'evening', '200', 'people', 'gathered', 'Passover', 'holiday', 'meal,', 'killing', 'least', '19', 'wounding', '100', 'others,', 'many', 'children.', 'OPEC', 'kingpin', 'Saudi', 'Arabia', 'signalled', 'Tuesday', 'could', 'act', 'alone', 'meet', 'predicted', 'i

### Part C: Compute the $k$-shingles of the documents for $k = 2$, where you shingle on the words, not letters.

In [11]:
def k_shingles_words(documents, k=2):
    all_shingles = []
    for document in documents:
        shingles = []
        size = len(document)
        for i, word in enumerate(document):
            if i >= size - k: break
            for j in range(i+1, i+k):
                word += (' ' + document[j])
            shingles.append(word)
            
        all_shingles.append(shingles)
        
    return all_shingles
        
print(k_shingles_words(stripped_documents)[0])

['t120 The', 'The Supreme', 'Supreme Court', 'Court Johnnesberg', 'Johnnesberg Friday', 'Friday postponed', 'postponed March', 'March 14', '14 hearing', 'hearing petition', 'petition government', 'government minister', 'minister Winnie', 'Winnie Mandela', 'Mandela prevent', 'prevent police', 'police reading', 'reading documents', 'documents seized', 'seized home,', 'home, SAPA', 'SAPA news', 'news agency', 'agency reported.', 'reported. David', 'David Wright', 'Wright Carlos', 'Carlos Delgado', 'Delgado homered', 'homered Jorge', 'Jorge Sosa', 'Sosa sixth', 'sixth time', 'time New', 'New York', 'York Mets', 'Mets snapped', 'snapped four-game', 'four-game losing', 'losing streak', 'streak 3-0', '3-0 victory', 'victory Detroit', 'Detroit Friday', 'Friday night.', 'night. US', 'US Defense', 'Defense Secretary', 'Secretary Robert', 'Robert Gates', 'Gates said', 'said Sunday', 'Sunday Iran', 'Iran yet', 'yet able', 'able make', 'make nuclear', 'nuclear weapon', 'weapon program', 'program pr

### Part D: Compute the $k$-shingles of the documents for $k = 3$, where you shingle on the characters, not words.

In [12]:
def k_shingles_characters(documents, k=3):
    all_shingles = []
    for doc in documents:
        shingles = []
        size = len(doc)
        for i in range(size-k):
            shingles.append(doc[i:i+k])
        all_shingles.append(shingles)
        
    return all_shingles

# It's easy to remove spaces - simply join the document on the empty string instead of on ' '.
joined = [' '.join(document) for document in stripped_documents]
print(k_shingles_characters(joined)[0])

['t12', '120', '20 ', '0 T', ' Th', 'The', 'he ', 'e S', ' Su', 'Sup', 'upr', 'pre', 'rem', 'eme', 'me ', 'e C', ' Co', 'Cou', 'our', 'urt', 'rt ', 't J', ' Jo', 'Joh', 'ohn', 'hnn', 'nne', 'nes', 'esb', 'sbe', 'ber', 'erg', 'rg ', 'g F', ' Fr', 'Fri', 'rid', 'ida', 'day', 'ay ', 'y p', ' po', 'pos', 'ost', 'stp', 'tpo', 'pon', 'one', 'ned', 'ed ', 'd M', ' Ma', 'Mar', 'arc', 'rch', 'ch ', 'h 1', ' 14', '14 ', '4 h', ' he', 'hea', 'ear', 'ari', 'rin', 'ing', 'ng ', 'g p', ' pe', 'pet', 'eti', 'tit', 'iti', 'tio', 'ion', 'on ', 'n g', ' go', 'gov', 'ove', 'ver', 'ern', 'rnm', 'nme', 'men', 'ent', 'nt ', 't m', ' mi', 'min', 'ini', 'nis', 'ist', 'ste', 'ter', 'er ', 'r W', ' Wi', 'Win', 'inn', 'nni', 'nie', 'ie ', 'e M', ' Ma', 'Man', 'and', 'nde', 'del', 'ela', 'la ', 'a p', ' pr', 'pre', 'rev', 'eve', 'ven', 'ent', 'nt ', 't p', ' po', 'pol', 'oli', 'lic', 'ice', 'ce ', 'e r', ' re', 'rea', 'ead', 'adi', 'din', 'ing', 'ng ', 'g d', ' do', 'doc', 'ocu', 'cum', 'ume', 'men', 'ent', 'nts'

# Question 5: Even More Minhash (Document Similarity)

### Part A

In [13]:
from binascii import crc32
import sys

p = 4294967311
n = 30

# Word shingles
word_signature_matrix = np.ndarray(shape=(n,len(stripped_documents)))
word_signature_matrix.fill(sys.maxsize)
for i in range(n):
    a, b = np.random.randint(p-1), np.random.randint(p-1)
    word_shingles = k_shingles_words(stripped_documents)
    
    for idx, document in enumerate(word_shingles):
        signatures = []
        for word in document:
            x = crc32(str.encode(word))
            value = (a*x + b) % p
            
            if not word_signature_matrix[i][idx] < value:
                word_signature_matrix[i][idx] = value
    
print(word_signature_matrix)

[[  2.63147800e+06   9.33698200e+06   1.12120910e+07   1.32671390e+07
    3.51558390e+07   2.63147800e+06]
 [  3.51215800e+06   4.52623830e+07   6.26854800e+07   4.90393730e+07
    1.31122530e+07   2.85068190e+07]
 [  4.38651510e+07   6.25279660e+07   7.47984300e+06   5.46072200e+06
    1.12457895e+08   2.28763290e+07]
 [  1.58465480e+07   1.96667530e+07   6.69884200e+06   7.52103390e+07
    3.09209570e+07   8.18601800e+06]
 [  3.99302620e+07   3.77920330e+07   1.20998600e+07   1.70909390e+07
    3.02720660e+07   3.99302620e+07]
 [  3.35240500e+06   6.82206000e+05   2.16914630e+07   2.47228320e+07
    1.13560780e+07   3.56633450e+07]
 [  7.77004500e+06   5.20203460e+07   2.37938940e+07   3.94202880e+07
    1.71163600e+07   2.50254700e+06]
 [  7.26045000e+06   1.75660200e+07   6.68082670e+07   4.36638140e+07
    3.96510880e+07   7.26045000e+06]
 [  1.39954430e+07   2.30123910e+07   1.72469320e+07   8.52987900e+06
    5.66208100e+06   1.39954430e+07]
 [  9.54256000e+05   4.91562600e+07  

In [14]:
# Character shingles
char_signature_matrix = np.ndarray(shape=(n,len(stripped_documents)))
char_signature_matrix.fill(sys.maxsize)
for i in range(n):
    a, b = np.random.randint(p-1), np.random.randint(p-1)
    char_shingles = k_shingles_characters(joined)
    
    for idx, document in enumerate(char_shingles):
        signatures = []
        for word in document:
            x = crc32(str.encode(word))
            value = (a*x + b) % p
            
            if not char_signature_matrix[i][idx] < value:
                char_signature_matrix[i][idx] = value
    
print(char_signature_matrix)

[[  6182352.    790596.   8540733.   2422151.  14411189.   9843478.]
 [ 11232138.   6181187.   1259303.  23389440.   1250030.  20354874.]
 [  1931344.   1931344.  22144456.   1606993.  24903416.   1931344.]
 [  1978934.   1978934.   2416765.   7186557.   2416765.   2416765.]
 [ 14358863.   2853049.    401586.  15936466.   7480201.   2853049.]
 [  7115388.   4761501.  13872642.   9024131.  13639651.  13872642.]
 [  7726852.   2927640.   2927640.  10734508.    212493.   7726852.]
 [  3148650.    410046.   7037274.   7481045.   7995123.   3148650.]
 [  3826156.   6213664.   1961236.   5590085.   1669069.   5590085.]
 [  5108539.   1146631.   8230792.   6067650.   1146631.   1146631.]
 [  3522639.    142375.    594954.   5758633.   1312424.    142375.]
 [   760157.    760157.   7583270.    233556.   4451546.    760157.]
 [  7047114.   7047114.   5539247.   5539247.   6844141.   7047114.]
 [  9539518.   4874017.   4874017.    632447.    824242.   3761109.]
 [  7333839.    580615.  18006797.

### Part B

In [15]:
# All we need to do is compare the column 0 to all other columns. The estimated similarity is the number of
# same values over the total number of values (30).